### PR TITLE
fix #3477 (nuke explosion not spawning for shield and unit hits)

### LINKED ISSUE #3477: Nuke impacting a flying unit at altitude over 20 elmo spawns no effect
See https://www.youtube.com/watch?v=6mTYu0A04uk

To replicate, place an enemy Nimbus over the silo and launch. Krows and Athenas will still trigger the CEG because they're low enough that the `ground` bit triggers.

The attempted solution in https://github.com/ZeroK-RTS/Zero-K/pull/3476 does not work.

### PR DESCRIPTION
**Pull request by Anarchid**
Gadget solution. Automatically also handles Funnelweb shields (which were also bork, like any other non-anti intercept above altitude 100).

Increased altitude valid for a "ground" hit because imo nuking a Nimbus should still trigger a ground version of the explosion.

### CODE REVIEW

File: LuaRules/Gadgets/exp_nuke_effect_chooser.lua [hunk 1]
```diff
@@ -42,8 +42,10 @@ function gadget:Explosion_GetWantedWeaponDef()
 end
 
 function gadget:Explosion(weaponID, px, py, pz, ownerID)
-	if (nux[weaponID] and py-GetGroundHeight(px,pz)>100) then
-		return true
+	if (nux[weaponID] and py-GetGroundHeight(px,pz)>200) then
+		Spring.SpawnCEG(defaultInterceptExplosion, px, py, pz, 0, 0, 0, nux[weaponID])
+	else
+		Spring.SpawnCEG(defaultSuccessExplosion, px, py, pz, 0, 0, 0, nux[weaponID])
```
Comment (sprunk) [inline LuaRules/Gadgets/exp_nuke_effect_chooser.lua]: IMO leave the success case to be unhandled. This way somebody can tweak the value in the weaponDef and it will take effect even without being aware of this gadget.
```suggestion
		return false
```

File: units/staticantinuke.lua [hunk 2]
```diff
@@ -87,7 +87,8 @@ unitDef = {
         subs    = 75,
       },
 
-      explosionGenerator      = [[custom:ANTINUKE]],
+      --spawning the intercept explosion is handled by exp_nuke_effect_chooser.lua
+      --explosionGenerator      = [[custom:ANTINUKE]],
```
Comment (sprunk) [inline units/staticantinuke.lua]: IMO it would still be good to have some sort of effect here because this projectile can also be bodyblocked by units (and instagibs most aircraft).

**Comment by sprunk** [comment]
The `unit = true` bit should probably be propagated to `LONDON_FLAT`'s sub-explosions as well while we're at it.

File: units/staticantinuke.lua (hunk 2 above)
Comment (Anarchid) [reply units/staticantinuke.lua]: There's a default explosion that antinuke has if not specified, but i guess `lrpc_expl` is prettier indeed

**Comment by Anarchid** [comment]
This approach does not require or make use of the `unit` bit, and the unit bit does not trigger on funnelweb shields anyway.

File: LuaRules/Gadgets/exp_nuke_effect_chooser.lua [hunk 3]
```diff
@@ -42,8 +42,10 @@ function gadget:Explosion_GetWantedWeaponDef()
 end
 
 function gadget:Explosion(weaponID, px, py, pz, ownerID)
-	if (nux[weaponID] and py-GetGroundHeight(px,pz)>100) then
-		return true
+	if (nux[weaponID] and py-GetGroundHeight(px,pz)>200) then
```
Comment (sprunk) [inline LuaRules/Gadgets/exp_nuke_effect_chooser.lua]: Funnel shield is pretty tall (weaponDef says 550 radius at 45 emitHeight) so 200 can still result in the interception gfx:
image


```suggestion
	if (nux[weaponID] and py-GetGroundHeight(px,pz)>600) then
```

Comment (Anarchid) [reply LuaRules/Gadgets/exp_nuke_effect_chooser.lua]: I think 600 is too much - at some point a Funnelweb interception actually *is* an interception - even if partial one, with a reduced rather than absent ground aoe radius.

Comment (sprunk) [reply LuaRules/Gadgets/exp_nuke_effect_chooser.lua]: Alright. Another question is sea: `GetGroundHeight` returns negative values there so at deep enough sea you can get the interception fx  when nuking ships:
image
```suggestion
	if (nux[weaponID] and py-math.max(0, GetGroundHeight(px,pz))>200) then
```

**Comment by Anarchid** [comment]
I think it makes sense to commit additional refinements directly tbh

File: LuaRules/Gadgets/exp_nuke_effect_chooser.lua (hunk 3 above)
Comment (Anarchid) [reply LuaRules/Gadgets/exp_nuke_effect_chooser.lua]: Good catch!
