### PR TITLE
More [Show Unit Stats] buttons (closes #4221)

### LINKED ISSUE #4221: Space + click to show unit stats should work on more location
Space + click is an awesome feature for new player.

However, it does not work on every location, it would be nice if it could be added everywhere.

Missing location:

- On selected units icons
image

- On queued units
image

- On selected unit
image

- On objective / tutorial screen
image

### PR DESCRIPTION
**Pull request by Birdulon**
Adds the ability to space+click on:
- [x] Selection panel - icon (single unit selected)
- [x] Selection panel - icon (multiple units selected)
- [x] Factory queue unit icons
- [x] Mission briefing tip unit icons

Additionally adds the Helptext to the new tooltip on the single unit selected icon, as it looked a bit lonely otherwise and I've had friends complain about that useful info being hidden behind a popup.
image

Edit: apparently titles don't link: closes #4221

### CODE REVIEW

**Comment by Licho1** [comment]
Btw. are those random whitespace changes necessary?

**Comment by Birdulon** [comment]
Nope, I can refactor them out if requested

File: LuaUI/Widgets/mission_galaxy_battle_handler.lua [hunk 1]
```diff
@@ -186,30 +190,47 @@ local function InitializeNewtonFirezones()
 	end
 end
 
+local function GetUnitDefFromIconFilename(filename)
+-- 	Spring.Echo('Searching for unit in filename: ' .. filename)
+	local name = string.match(filename, "unitpics/(%w+).png")
+	if name then
+-- 		Spring.Echo('Found unitname: ' .. name)
+		local udef = UnitDefNames[name]
+		if name then
```
Comment (sprunk) [inline LuaUI/Widgets/mission_galaxy_battle_handler.lua:199]: typo?
```suggestion
		if udef then
```

File: LuaUI/Widgets/gui_chili_integral_menu.lua [hunk 2]
```diff
@@ -973,25 +991,40 @@ local function QueueClickFunc(mouse, right, alt, ctrl, meta, shift, queueCmdID,
...
+				if cmddsc then
+					local udid = UnitDefNames[cmddsc.name]
+					if udid then
+						local x, y = spGetMouseState()
+						WG.MakeStatsWindow(udid, x, y, factoryUnitID)
+					end
+				end
+			end
+		else
 		QueueClickFunc(mouse, right, alt, ctrl, meta, shift, cmdID, factoryUnitID, queueBlock)
```
Comment (sprunk) [inline LuaUI/Widgets/gui_chili_integral_menu.lua:1017]:
```suggestion
			QueueClickFunc(mouse, right, alt, ctrl, meta, shift, cmdID, factoryUnitID, queueBlock)
```

File: LuaUI/Widgets/gui_chili_selections_and_cursortip.lua [hunk 3]
```diff
@@ -47,7 +49,10 @@ local selectionTooltip = "\n" .. green .. WG.Translate("interface", "lmb") .. ":
 	green .. WG.Translate("interface", "rmb") .. ": " .. WG.Translate("interface", "deselect") .. "\n" ..
 	green .. WG.Translate("interface", "shift") .. "+" .. WG.Translate("interface", "lmb") .. ": " .. WG.Translate("interface", "select_type") .. "\n" ..
 	green .. WG.Translate("interface", "shift") .. "+" .. WG.Translate("interface", "rmb") .. ": " .. WG.Translate("interface", "deselect_type") .. "\n" ..
-	green .. WG.Translate("interface", "mmb") .. ": " .. WG.Translate("interface", "go_to")
+	green .. WG.Translate("interface", "mmb") .. ": " .. WG.Translate("interface", "go_to") ..
+	"\n" .. green .. WG.Translate("interface", "space_click_show_stats")
```
Comment (sprunk) [inline LuaUI/Widgets/gui_chili_selections_and_cursortip.lua:53]: style consistency
```suggestion
	green .. WG.Translate("interface", "mmb") .. ": " .. WG.Translate("interface", "go_to") .. "\n" .. 
	green .. WG.Translate("interface", "space_click_show_stats")
```

**Comment by sprunk** [comment]
I am unsure if adding all the "if meta and button == 1 blabla WG.MakeStatsWindow" code everywhere is needed. Possibly all of those just need the unit-like tooltip ("Glaive - Raider Bot" etc) and space-click could trigger off that.

That said if the current code works it may well be good enough, maybe let GF say something.

File: LuaUI/Widgets/gui_chili_integral_menu.lua [hunk 4]
```diff
@@ -16,8 +16,26 @@ end
 
 --------------------------------------------------------------------------------
 --------------------------------------------------------------------------------
--- Configuration
+-- Spring localizations
+local spEcho = Spring.Echo
```
Comment (GoogleFrog) [inline LuaUI/Widgets/gui_chili_integral_menu.lua:20]: I like to leave Echo unlocalised because it should not appear in normal circumstances and makes searching the repository for echos easier.
