### PR TITLE
Fix #1396 bug with wolverine claws not spawned

### LINKED ISSUE #1396: Wolverine Claws are not spawned if Wolverine dies
This should now be fixable with ProjectileDestroyed and Spring.GetProjectileTeamID.

### PR DESCRIPTION
**Pull request by N0U**

### CODE REVIEW

File: LuaRules/Gadgets/unit_explosion_spawner.lua [hunk 1]
```diff
@@ -48,22 +48,26 @@ function gadget:Explosion_GetWantedWeaponDef()
 	return wantedList
 end
 
-function gadget:Explosion(w, x, y, z, owner)
```
Comment (ashdnazg) [inline LuaRules/Gadgets/unit_explosion_spawner.lua]: why use ProjectileDestroyed and not Explosion?

Comment (N0U) [inline LuaRules/Gadgets/unit_explosion_spawner.lua]: Explosion doesn't give projectile id and when wolverine die, owner id become invalid, so there is no way to find team id. Before this script just ignored any projectiles with a dead owner.
